### ISSUE TITLE
userの一覧リストが表示されない

### ISSUE THREAD

**Issue by AyanoNakai** [AyanoNakai/ToDo#1]
mySQLの方のtable(user)にはリストが作成されているのですが, localhost:8080/usersでは一覧が表示されません. 
アドバイスお願いいたします.

**Comment by muretti0114** [comment]
中井さん　お疲れさんです．

UserControllerのshowAllUsers()で，
model.addAttribute("allulist", userList);
としていますね？なので，テンプレートの中では，allulistで
リストを取り出さねばなりません．
つまり
alluserlist.html の下記の箇所を書き換えればＯＫです．
        <tr th:each="p: ${ulist}">
　→
        <tr th:each="p: ${allulist}">

やってみてください

**Comment by AyanoNakai** [comment]
> 中井さん　お疲れさんです．
> 
> UserControllerのshowAllUsers()で，
> model.addAttribute("allulist", userList);
> としていますね？なので，テンプレートの中では，allulistで
> リストを取り出さねばなりません．
> つまり
> alluserlist.html の下記の箇所を書き換えればＯＫです．
> 
> 　→
> やってみてください

解決しました！ありがとうございます！
